// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	crawlerModel "lexicon/indonesia-supreme-court-crawler/crawler/models"
	scrapperModel "lexicon/indonesia-supreme-court-crawler/scrapper/models"
)

type Extraction struct {
	ID            string
	UrlFrontierID string
	SiteContent   *string
	ArtifactLink  *string
	RawPageLink   *string
	Metadata      scrapperModel.ExtractionMetadata
	Language      string
	PageHash      *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UrlFrontier struct {
	ID      string
	Domain  string
	Url     string
	Crawler string
	// 0: Pending, 1: Crawled, 2: Changed
	Status    int16
	Metadata  crawlerModel.UrlFrontierMetadata
	CreatedAt time.Time
	UpdatedAt time.Time
}
